version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: order_table_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  spring:
    container_name: spring
    build: .
    ports:
      - 1234:1234
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/order_table_db
      - spring.datasource.username=postgres
      - spring.datasource.password=123
      - spring.kafka.bootstrap-servers=blabla:9092
    depends_on:
      postgres:
        condition: service_healthy
